version: '3.5'
services:
  hapi:
    container_name: hapi
    build:
      context: '.'
    environment:
      - VIRTUAL_HOST=${V_HOST}
      - VIRTUAL_PORT=${V_PORT}
      - LETSENCRYPT_HOST=sacly.isaacmanubag.com
      - LETSENCRYPT_EMAIL=isaac_manubag@yahoo.com
      - WAIT_HOSTS=mongo:27017
    expose:
      - '${EXPOSE_PORT}'
    volumes:
      - .:/usr/src/app
    networks:
      default:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
networks:
  default:
    external:
      name: nginx-proxy
