version: '3.5'
services:
  hapi:
    container_name: hapi
    build:
      context: '.'
    environment:
      VIRTUAL_HOST: sacly.isaacmanubag.com
      VIRTUAL_PORT: 3000
      WAIT_HOSTS: mongo:27017
    expose:
      - 80
    volumes:
      - .:/usr/src/app
    networks:
      default:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
networks:
  default:
    external:
      name: nginx-proxy