version: '3.5'
services:
  hapi:
    container_name: hapi
    build:
      context: '.'
    ports:
      - '3000:3000'
    expose:
      - 3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
